FROM python:3.11-slim-buster
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
# set time zone
ENV TZ=Europe/Stockholm

# create and use non-root user.. (requires us to use a port number higher than 1024)
RUN adduser -u 1000 \
  --disabled-password \
  --home /datapump-usr \
  --gecos '' datapump-usr \
  && chown -R datapump-usr /datapump-usr


USER datapump-usr

ENTRYPOINT ["python", "datapump.py"]

