apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: docbot
      context: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./devops/k8s/local/*.yaml
deploy:
  statusCheck: false
  kubectl: {}