apiVersion: skaffold/v4beta5
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: embeddings-worker
      context: .
      docker:
        dockerfile: Dockerfile.worker
manifests:
  rawYaml:
    - ./devops/k8s/local/openai-secret.yaml
    - ./devops/k8s/local/prompt-secret.yaml
    - ./devops/k8s/local/one-off-embeddings-updater.yaml
deploy:
  statusCheck: false
  kubectl: {}

