apiVersion: skaffold/v4beta5
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: docbot
      context: .
      docker:
        dockerfile: Dockerfile
    - image: db-mig 
      context: ./migrations
manifests:
  rawYaml:
    - ./devops/k8s/local/postgres.yaml
    - ./devops/k8s/local/db-migration.yaml
    - ./devops/k8s/local/openai-secret.yaml
    - ./devops/k8s/local/prompt-secret.yaml
    - ./devops/k8s/local/redis-stack-server.yaml
    - ./devops/k8s/local/chatbot.yaml
deploy:
  statusCheck: false
  kubectl: {}

