apiVersion: apps/v1
kind: Deployment
metadata:
  name: docbot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docbot-app
  template:
    metadata:
      labels:
        app: docbot-app
    spec:
      containers:
        - env:
            - name: CHATBOT_LANG
              value: "en"
            - name: SEMANTIC_CACHE_ENABLED
              value: "true"
            - name: SEMANTIC_CACHE_MIN_SIMILARITY_SCORE
              value: "0.97"
            - name: SECTIONS_MIN_SIMILARITY_SCORE
              value: "0.81"
            - name: REDIS_HOST
              value: redis-service
            - name: SPAENVIRONMENT
              value: "local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: api-key
            - name: PROMPT_INST_EN
              valueFrom:
                secretKeyRef:
                  name: prompt
                  key: instructions-en
            - name: PROMPT_INST
              valueFrom:
                secretKeyRef:
                  name: prompt
                  key: instructions
          name: docbot-container
          image: docbot
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: docbot-service
spec:
  type: LoadBalancer
  selector:
    app: docbot-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
